
export * from './Icon';
export type { FariIconVue } from './vue.ts';
export * from './js';
export type { IconName } from './Icon';
declare const CheckIcon: FariIconVue;
declare const ChevronLeftIcon: FariIconVue;
declare const ChevronRightIcon: FariIconVue;
declare const CloudIcon: FariIconVue;
declare const ConnectIcon: FariIconVue;
declare const CrossIcon: FariIconVue;
declare const DisconnectIcon: FariIconVue;
declare const DroneIcon: FariIconVue;
declare const EraseIcon: FariIconVue;
declare const MenuIcon: FariIconVue;
declare const OvercastIcon: FariIconVue;
declare const PlayIcon: FariIconVue;
declare const ResetMapIcon: FariIconVue;
declare const SettingsIcon: FariIconVue;
declare const SunOutlineIcon: FariIconVue;
declare const SunIcon: FariIconVue;
declare const TemperatureIcon: FariIconVue;
declare const TooltipIcon: FariIconVue;
declare const UndoIcon: FariIconVue;